### PR TITLE
Added some great tweets

### PR DESCRIPTION
**Pull request by byemc**

### CODE REVIEW

**Comment by byemc** [comment]
WAIT NO DON'T MERGE
I MADE A MISTAKE

**Comment by annasajkh** [comment]
i saw it lol

**Comment by byemc** [comment]
k fixed

**Comment by annasajkh** [comment]
i don't even know if this even work cuz replit

**Comment by byemc** [comment]
ah

**Comment by annasajkh** [comment]
wait i will remove the quote tweet first

**Comment by byemc** [comment]
neat

**Comment by byemc** [comment]
Now I shall get random pings from the bot, amazing

**Pull request merged**
